In [1]:
####################################
# MODELAGEM ENSEMBLE RANDOM FOREST #
####################################

# ===============================
# 1. IMPORTAÇÃO DAS BIBLIOTECAS
# ===============================
import os
import glob
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

import warnings
warnings.filterwarnings("ignore")

PASTA_TREINO = "DADOS DE TREINAMENTO"
PASTA_ENTRADA = "ENTRADA"

print("Bibliotecas importadas com sucesso.")


# ============================================================
# 2. PARÂMETROS DO MODELO (solicitados via campo de texto)
# ============================================================
def perguntar(texto, padrao, tipo=str):
    '''Pergunta um valor ao usuário via campo de texto (input),
    retornando o valor padrão caso o campo seja deixado em branco.'''
    resposta = input(f"{texto} [padrão = {padrao}]: ").strip()
    if resposta == "":
        return padrao
    if tipo == int:
        return int(resposta)
    if tipo == float:
        return float(resposta)
    if tipo == bool:
        return resposta.lower() in ("s", "sim", "y", "yes", "true", "1")
    return resposta


def perguntar_opcao(texto, opcoes, padrao_idx=0):
    '''Apresenta uma lista numerada de opções e retorna a opção escolhida pelo usuário.
    Repete a pergunta até que uma escolha válida seja informada, evitando erros de digitação.'''
    print(f"\n{texto}")
    for i, opcao in enumerate(opcoes, start=1):
        marcador = " (padrão)" if (i - 1) == padrao_idx else ""
        print(f"  {i}. {opcao}{marcador}")
    while True:
        resposta = input(f"Escolha uma opção [1-{len(opcoes)}] (Enter = padrão): ").strip()
        if resposta == "":
            return opcoes[padrao_idx]
        if resposta.isdigit():
            indice = int(resposta)
            if 1 <= indice <= len(opcoes):
                return opcoes[indice - 1]
        print(f"Opção inválida. Digite um número entre 1 e {len(opcoes)}.")


print("\n*** Parâmetros da Random Forest ***\n")

n_estimators = perguntar("Quantidade de árvores", 100, int)

criterion_escolhido = perguntar_opcao("Critério de divisão:", ["gini", "entropia", "log_loss"], padrao_idx=0)

# O scikit-learn exige os termos em inglês ('gini', 'entropy', 'log_loss'); aqui traduzimos
# a escolha do usuário (feita em português) para o valor aceito pelo RandomForestClassifier.
mapa_criterion = {"gini": "gini", "entropia": "entropy", "log_loss": "log_loss"}
criterion = mapa_criterion[criterion_escolhido]

opcao_max_depth = perguntar_opcao(
    "Profundidade máxima das árvores:",
    ["Sem limite (none)", "Informar um valor numérico"],
    padrao_idx=0
)
if opcao_max_depth == "Sem limite (none)":
    max_depth = None
else:
    max_depth = perguntar("Profundidade máxima das árvores", 10, int)

min_samples_split = perguntar("Número mínimo de amostras para dividir um nó", 2, int)

min_samples_leaf = perguntar("Número mínimo de amostras em uma folha", 1, int)

opcao_max_features = perguntar_opcao(
    "Número de features consideradas em cada divisão:",
    ["sqrt", "log2", "none"],
    padrao_idx=0
)
max_features = None if opcao_max_features == "none" else opcao_max_features

opcao_bootstrap = perguntar_opcao(
    "Usar amostragem bootstrap nos dados de treinamento?",
    ["Sim", "Não"],
    padrao_idx=0
)
bootstrap = (opcao_bootstrap == "Sim")

random_state = 42

test_size = perguntar(
    "Proporção dos dados de treinamento reservada para validação interna (0 a 0.9; use 0 para treinar com 100%)",
    0.2, float
)

print("\n=== Parâmetros definidos ===")
print(f"n_estimators      = {n_estimators}")
print(f"criterion         = {criterion}")
print(f"max_depth         = {max_depth}")
print(f"min_samples_split = {min_samples_split}")
print(f"min_samples_leaf  = {min_samples_leaf}")
print(f"max_features      = {max_features}")
print(f"bootstrap         = {bootstrap}")
print(f"random_state      = {random_state}")
print(f"test_size         = {test_size}")


# =============================================
# 3. CARREGAMENTO DOS DADOS DE TREINAMENTO
# =============================================
def localizar_planilha(pasta):
    arquivos = glob.glob(os.path.join(pasta, "*.xlsx")) + glob.glob(os.path.join(pasta, "*.xls"))
    if len(arquivos) == 0:
        raise FileNotFoundError(f"Nenhum arquivo .xlsx/.xls encontrado na pasta '{pasta}'.")
    if len(arquivos) > 1:
        print(f"Aviso: mais de um arquivo encontrado em '{pasta}'. Usando o primeiro: {arquivos[0]}")
    return arquivos[0]


print("\n=== Carregando dados de treinamento ===")
caminho_treino = localizar_planilha(PASTA_TREINO)
print(f"Arquivo de treinamento encontrado: {caminho_treino}")

df_treino = pd.read_excel(caminho_treino)

if "Classe" not in df_treino.columns:
    raise ValueError("A planilha de treinamento precisa conter uma coluna chamada 'Classe'.")

print(f"Dimensões dos dados: {df_treino.shape[0]} linhas x {df_treino.shape[1]} colunas")
display(df_treino.head())


# =====================================================================
# 4. PRÉ-PROCESSAMENTO
# =====================================================================
X = df_treino.drop(columns=["Classe"]).copy()
y = df_treino["Classe"].copy()

colunas_features = list(X.columns)

# Tratamento de valores ausentes simples (preenchimento pela mediana)
# Usamos pd.api.types.is_numeric_dtype em vez de comparar com "object" diretamente,
# pois versões mais novas do pandas podem usar o tipo "string" para colunas de texto.
for col in X.columns:
    if pd.api.types.is_numeric_dtype(X[col]):
        X[col] = X[col].fillna(X[col].median())
    else:
        X[col] = X[col].fillna("Desconhecido")

# Codificação de variáveis categóricas (Label Encoding por coluna - atribuição de número à variável)
# Na construção de árvores, o Label Encoding (atribuição de números sequenciais 1,2,3...) não prejudica
# a modelagem. Em regressão, seria melhor usar o One-Hot Encoding. Aqui não faz diferença.
encoders = {}
for col in X.columns:
    if not pd.api.types.is_numeric_dtype(X[col]):
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col].astype(str))
        encoders[col] = le

# Codificação da classe alvo
le_classe = LabelEncoder()
y_encoded = le_classe.fit_transform(y.astype(str))

print("\nColunas de features:", colunas_features)
print("Classes encontradas:", list(le_classe.classes_))


# ==========================================
# 5. TREINAMENTO DO MODELO RANDOM FOREST
# ==========================================
print("\n=== Treinando o modelo ===")

if test_size and test_size > 0:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_encoded, test_size=test_size, random_state=random_state,
        stratify=y_encoded if len(set(y_encoded)) > 1 else None
    )

    modelo = RandomForestClassifier(
        n_estimators=n_estimators,
        criterion=criterion,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        bootstrap=bootstrap,
        random_state=random_state,
    )
    modelo.fit(X_train, y_train)

    y_pred_test = modelo.predict(X_test)
    acuracia = accuracy_score(y_test, y_pred_test)

    print(f"Acurácia na validação interna ({test_size*100:.0f}% dos dados): {acuracia*100:.2f}%\n")
    print("Relatório de classificação:")
    print(classification_report(y_test, y_pred_test, target_names=[str(c) for c in le_classe.classes_]))

    # Treina o modelo final com todos os dados disponíveis
    modelo_final = RandomForestClassifier(
        n_estimators=n_estimators,
        criterion=criterion,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        bootstrap=bootstrap,
        random_state=random_state,
    )
    modelo_final.fit(X, y_encoded)
else:
    modelo_final = RandomForestClassifier(
        n_estimators=n_estimators,
        criterion=criterion,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        bootstrap=bootstrap,
        random_state=random_state,
    )
    modelo_final.fit(X, y_encoded)
    print("Modelo treinado com 100% dos dados de treinamento (sem validação interna).")

print("Treinamento concluído.")


# ===================================================
# 6. CARREGAMENTO DO INDIVÍDUO A SER CLASSIFICADO
# ===================================================
print("\n=== Carregando dados de entrada ===")
caminho_entrada = localizar_planilha(PASTA_ENTRADA)
print(f"Arquivo de entrada encontrado: {caminho_entrada}")

df_entrada = pd.read_excel(caminho_entrada)

# Garante que a planilha de entrada tenha as mesmas colunas de features do treinamento
colunas_faltantes = [c for c in colunas_features if c not in df_entrada.columns]
if colunas_faltantes:
    raise ValueError(f"A planilha de entrada não possui as colunas: {colunas_faltantes}")

X_novo = df_entrada[colunas_features].copy()

# Aplica o mesmo tratamento/codificação usado no treinamento
for col in X_novo.columns:
    if col in encoders:
        le = encoders[col]
        X_novo[col] = X_novo[col].astype(str).fillna("Desconhecido")
        # Trata categorias não vistas no treinamento
        X_novo[col] = X_novo[col].apply(lambda v: v if v in le.classes_ else le.classes_[0])
        X_novo[col] = le.transform(X_novo[col])
    else:
        X_novo[col] = X_novo[col].fillna(X[col].median())

print(f"\n{len(X_novo)} indivíduo(s) carregado(s) para classificação (uma predição será feita para cada linha da planilha):")
tabela_individuos = df_entrada[colunas_features].copy()
tabela_individuos.index = range(1, len(tabela_individuos) + 1)
tabela_individuos.index.name = "Indivíduo"
display(tabela_individuos)


# =============================================================================
# 7. CLASSIFICAÇÃO E RESULTADO DA VOTAÇÃO DAS ÁRVORES
# (o laço abaixo percorre TODAS as linhas/indivíduos da planilha de ENTRADA,
#  gerando uma predição e um resultado de votação para cada um deles)
# =============================================================================
for idx in range(len(X_novo)):
    linha = X_novo.iloc[[idx]]

    # Votos individuais de cada árvore da floresta
    votos_codificados = [int(arvore.predict(linha)[0]) for arvore in modelo_final.estimators_]
    votos_classes = le_classe.inverse_transform(votos_codificados)

    contagem_votos = pd.Series(votos_classes).value_counts()

    # Predição final por maioria (equivalente ao .predict do RandomForest)
    classe_predita = le_classe.inverse_transform(modelo_final.predict(linha))[0]

    # Probabilidades (proporção de árvores que votaram em cada classe)
    probabilidades = modelo_final.predict_proba(linha)[0]

    print("=" * 60)
    print(f"Indivíduo {idx + 1} de {len(X_novo)}")
    print("=" * 60)
    print("\nDados do indivíduo:")
    dados_individuo = df_entrada.iloc[[idx]][colunas_features].copy()
    dados_individuo.index = [idx + 1]
    dados_individuo.index.name = "Indivíduo"
    display(dados_individuo)
    print("\nVotação das árvores (contagem simples da quantidade de votos por classe):")
    for classe, votos in contagem_votos.items():
        pct = votos / len(votos_classes) * 100
        print(f"  {classe:>20s} : {votos:4d} votos  ({pct:5.1f}%)")

    print(f"\n>>> CLASSE PREDITA (maioria dos votos): {classe_predita} <<<\n")

    resultado_df = pd.DataFrame({
        "Classe": le_classe.classes_,
        "Nº de árvores que votaram": [contagem_votos.get(c, 0) for c in le_classe.classes_],
        "Probabilidade (%) - média das p(classe)": (probabilidades * 100).round(2)
    }).sort_values("Nº de árvores que votaram", ascending=False).reset_index(drop=True)

    display(resultado_df)
    print("\n")


# =================================
# 8. IMPORTÂNCIA DAS VARIÁVEIS
# =================================
importancias = pd.DataFrame({
    "Feature": colunas_features,
    "Importância": modelo_final.feature_importances_
}).sort_values("Importância", ascending=False).reset_index(drop=True)

print("\n=== Importância das variáveis no modelo ===")
display(importancias)

Bibliotecas importadas com sucesso.

*** Parâmetros da Random Forest ***

Quantidade de árvores [padrão = 100]:  100

Critério de divisão:
  1. gini (padrão)
  2. entropia
  3. log_loss

Escolha uma opção [1-3] (Enter = padrão):  2

Profundidade máxima das árvores:
  1. Sem limite (none) (padrão)
  2. Informar um valor numérico

Escolha uma opção [1-2] (Enter = padrão):
Número mínimo de amostras para dividir um nó [padrão = 2]:
Número mínimo de amostras em uma folha [padrão = 1]:

Número de features consideradas em cada divisão:
  1. sqrt (padrão)
  2. log2
  3. none

Escolha uma opção [1-3] (Enter = padrão):

Usar amostragem bootstrap nos dados de treinamento?
  1. Sim (padrão)
  2. Não

Escolha uma opção [1-2] (Enter = padrão):
Proporção dos dados de treinamento reservada para validação interna (0 a 0.9; use 0 para treinar com 100%) [padrão = 0.2]:  0.2

=== Parâmetros definidos ===
n_estimators      = 100
criterion         = entropy
max_depth         = None
min_samples_split = 2
min_samples_leaf  = 1
max_features      = sqrt
bootstrap         = True
random_state      = 42
test_size         = 0.2

=== Carregando dados de treinamento ===
Arquivo de treinamento encontrado: DADOS DE TREINAMENTO\Dados de Treinamento - prontos 2.xlsx
Dimensões dos dados: 30 linhas x 4 colunas

  Faixa de idades Faixa de logs de renda Faixa de tickets médios  Classe
0     Acima de 50                  Média                    Alto       1
1     Acima de 50                  Média                    Alto       1
2     Acima de 50                  Baixa                    Alto       1
3     Acima de 50                   Alta                    Alto       1
4     Acima de 50                  Baixa                   Médio       0

Colunas de features: ['Faixa de idades', 'Faixa de logs de renda', 'Faixa de tickets médios']
Classes encontradas: ['0', '1']

=== Treinando o modelo ===
Acurácia na validação interna (20% dos dados): 83.33%

Relatório de classificação:
              precision    recall  f1-score   support

           0       0.75      1.00      0.86         3
           1       1.00      0.67      0.80         3

    accuracy                           0.83         6
   macro avg       0.88      0.83      0.83         6
weighted avg       0.88      0.83      0.83         6

Treinamento concluído.

=== Carregando dados de entrada ===
Arquivo de entrada encontrado: ENTRADA\Indivíduos.xlsx

11 indivíduo(s) carregado(s) para classificação (uma predição será feita para cada linha da planilha):

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
1                   31–50                  Média                   Médio
2             Acima de 50                   Alta                    Alto
3                   31–50                  Média                    Alto
4                   31–50                  Baixa                   Baixo
5             Acima de 50                  Baixa                   Baixo
6             Acima de 50                  Baixa                   Médio
7             Acima de 50                  Média                   Médio
8             Acima de 50                  Média                    Alto
9             Acima de 50                  Baixa                    Alto
10            Acima de 50                   Alta                    Alto
11            Acima de 50                   Alta                   Médio

============================================================
Indivíduo 1 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
1                   31–50                  Média                   Médio

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   94 votos  ( 94.0%)
                     0 :    6 votos  (  6.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         94                                    93.72
1      0                          6                                     6.28

============================================================
Indivíduo 2 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
2             Acima de 50                   Alta                    Alto

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   92 votos  ( 92.0%)
                     0 :    8 votos  (  8.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         92                                     92.0
1      0                          8                                      8.0

============================================================
Indivíduo 3 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
3                   31–50                  Média                    Alto

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   99 votos  ( 99.0%)
                     0 :    1 votos  (  1.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         99                                     99.0
1      0                          1                                      1.0

============================================================
Indivíduo 4 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
4                   31–50                  Baixa                   Baixo

Votação das árvores (contagem simples da quantidade de votos por classe):
                     0 :   98 votos  ( 98.0%)
                     1 :    2 votos  (  2.0%)

>>> CLASSE PREDITA (maioria dos votos): 0 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      0                         98                                    82.76
1      1                          2                                    17.24

============================================================
Indivíduo 5 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
5             Acima de 50                  Baixa                   Baixo

Votação das árvores (contagem simples da quantidade de votos por classe):
                     0 :   98 votos  ( 98.0%)
                     1 :    2 votos  (  2.0%)

>>> CLASSE PREDITA (maioria dos votos): 0 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      0                         98                                    94.56
1      1                          2                                     5.44

============================================================
Indivíduo 6 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
6             Acima de 50                  Baixa                   Médio

Votação das árvores (contagem simples da quantidade de votos por classe):
                     0 :   96 votos  ( 96.0%)
                     1 :    4 votos  (  4.0%)

>>> CLASSE PREDITA (maioria dos votos): 0 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      0                         96                                    71.37
1      1                          4                                    28.63

============================================================
Indivíduo 7 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
7             Acima de 50                  Média                   Médio

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   96 votos  ( 96.0%)
                     0 :    4 votos  (  4.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         96                                    96.38
1      0                          4                                     3.62

============================================================
Indivíduo 8 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
8             Acima de 50                  Média                    Alto

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   99 votos  ( 99.0%)
                     0 :    1 votos  (  1.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         99                                     99.0
1      0                          1                                      1.0

============================================================
Indivíduo 9 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
9             Acima de 50                  Baixa                    Alto

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   84 votos  ( 84.0%)
                     0 :   16 votos  ( 16.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         84                                     84.9
1      0                         16                                     15.1

============================================================
Indivíduo 10 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
10            Acima de 50                   Alta                    Alto

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   92 votos  ( 92.0%)
                     0 :    8 votos  (  8.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         92                                     92.0
1      0                          8                                      8.0

============================================================
Indivíduo 11 de 11
============================================================

Dados do indivíduo:

          Faixa de idades Faixa de logs de renda Faixa de tickets médios
Indivíduo
11            Acima de 50                   Alta                   Médio

Votação das árvores (contagem simples da quantidade de votos por classe):
                     1 :   78 votos  ( 78.0%)
                     0 :   22 votos  ( 22.0%)

>>> CLASSE PREDITA (maioria dos votos): 1 <<<

  Classe  Nº de árvores que votaram  Probabilidade (%) - média das p(classe)
0      1                         78                                     81.2
1      0                         22                                     18.8

=== Importância das variáveis no modelo ===

                   Feature  Importância
0   Faixa de logs de renda     0.412959
1  Faixa de tickets médios     0.339222
2          Faixa de idades     0.247819